### ISSUE TITLE
GetBanners

### ISSUE THREAD

**Issue by sahinrasit** [burakoner/Paribu.Net#7]
Exception has occurred: CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in Paribu.Net.dll: 'Object reference not set to an instance of an object.'
   at Paribu.Net.ParibuClient.GetBanners(CancellationToken ct) in /Users/rasitsahin/Desktop/dataBot/Paribu.Net/Paribu.Net/ParibuClient.cs:line 61
   at Paribu.Net.Examples.Program.Main(String[] args) in /Users/rasitsahin/Desktop/dataBot/Paribu.Net/Paribu.Net.Examples/Program.cs:line 15

**Comment by burakoner** [comment]
Gelen veri null mı diye kontrol etmen yeterli. Paribu'da veri yoksa doğal olarak null dönüyor.
